"""Publish the post generated by the research agent to LinkedIn."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from .utils import LinkedInClient, LinkedInSettings, linkedin_settings


def publish_post(
    full_post: str,
    hashtags: list[str] | str | None = None,
    *,
    client: LinkedInClient | None = None,
    settings: LinkedInSettings | None = None,
    headless: bool = False,
) -> dict[str, str | None]:
    """Publish a generated ``full_post`` and its separate hashtag list."""
    if client is None:
        client = LinkedInClient(settings or linkedin_settings())
    return client.publish(full_post, headless=headless, hashtags=hashtags)


def publish_post_plan(
    post_plan: Mapping[str, Any] | Any,
    *,
    client: LinkedInClient | None = None,
    settings: LinkedInSettings | None = None,
    headless: bool = False,
) -> dict[str, str | None]:
    """Publish a mapping or Pydantic model containing ``full_post`` and ``hashtags``."""
    if hasattr(post_plan, "model_dump"):
        post_plan = post_plan.model_dump()
    if not isinstance(post_plan, Mapping):
        raise TypeError("post_plan must be a mapping or expose model_dump()")
    return publish_post(
        str(post_plan.get("full_post", "")),
        post_plan.get("hashtags"),
        client=client,
        settings=settings,
        headless=headless,
    )
